AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eks-automation-lambda

Resources:
  EKSAutomationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          UsagePlanName: eks-automation-usage-plan
          CreateUsagePlan: PER_API
          Description: Usage plan for EKS Automation API
          Quota:
            Limit: 5000
            Period: MONTH
          Throttle:
            BurstLimit: 500
            RateLimit: 100
          Tags:
            - Key: finops_project_name
              Value: csvd_platformbaseline
            - Key: finops_project_number
              Value: fs0000000078
            - Key: finops_project_role
              Value: csvd_platformbaseline_app
            - Key: environment
              Value: development
            - Key: environment_abbr
              Value: dev
            - Key: organization
              Value: census:ocio:csvd
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Tags:
        environment: development
        environment_abbr: dev
        organization: census:ocio:csvd
        finops_project_name: csvd_platformbaseline
        finops_project_number: fs0000000078
        finops_project_role: csvd_platformbaseline_app
  GitLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: git-lambda-layer
      Description: Git Lambda Layer
      ContentUri: s3://eks-automation-lambda-s3-bucket/layer.zip
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
  EKSAutomationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: eks_automation/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Events:
        EKSAutomation:
          Type: Api
          Properties:
            RestApiId: !Ref EKSAutomationApi
            Path: /EKSAutomation
            Method: post
            Auth:
              ApiKeyRequired: true
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
          - Sid: SSMDescribeParametersPolicy
            Effect: Allow
            Action:
            - ssm:DescribeParameters
            Resource: '*'
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
            - ssm:GetParameters
            - ssm:GetParameter
            Resource: '*'
      VpcConfig:
        SecurityGroupIds:
          - sg-03cbf2a626ed55c7e
        SubnetIds:
          - subnet-05192178ac094f639
          - subnet-022370a5a03585376
      PropagateTags: True
      Tags:
        environment: development
        environment_abbr: dev
        organization: census:ocio:csvd
        finops_project_name: csvd_platformbaseline
        finops_project_number: fs0000000078
        finops_project_role: csvd_platformbaseline_app
      Layers:
        - !Ref GitLambdaLayer
      Environment:
        Variables:
          HOME: /tmp
Outputs:
  EKSAutomationApi:
    Description: "API Gateway endpoint URL for Prod stage for EKS Automation function"
    Value: !Sub "https://${EKSAutomationApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/EKSAutomation/"
  EKSAutomationFunction:
    Description: "EKS Automation Lambda Function ARN"
    Value: !GetAtt EKSAutomationFunction.Arn
  EKSAutomationFunctionIamRole:
    Description: "Implicit IAM Role created for EKS Automation function"
    Value: !GetAtt EKSAutomationFunctionRole.Arn
