name: GitHub Client Integration Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    if: ${{ github.server_url == 'https://github.com' }}
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: template_automation/requirements.txt
      
      - name: Install dependencies
        run: |
          cd template_automation
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run integration tests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN_SECRET_NAME: /dev/secret/ssh/dont/tell
          GITHUB_API: "https://api.github.com"  # Can be overridden with vars if needed
          GITHUB_ORG_NAME: ${{ github.repository_owner }}
        run: |
          cd template_automation
          python -m pytest tests/ -v -m integration
